### ISSUE TITLE
When will the code be released ?

### ISSUE THREAD

**Issue by Buanma** [xindeng98/PointVector#1]
May I ask when the code will be released?

**Comment by xindeng98** [comment]
> May I ask when the code will be released?

Since we used pointnext as a baseline, our code has been integrated into PointNext repo long ago. I forgot to update it in github and arxiv. 
[https://guochengqian.github.io/PointNeXt/projects/pointvector/](https://guochengqian.github.io/PointNeXt/projects/pointvector/)

**Comment by Buanma** [comment]
Thank you very much for your timely reply!
